# eventlog-reactors managed body-sha256=77bb5739b7fd106b28925f40c74e79caf5bd0f9fb179caee57cb306248f007f6
# Generated by eventlog setup. Load eventlog_reactors() into an existing workspace panes list.
def eventlog_reactors():
    committer = herdr.tab("composer-2.5-fast" + ": commit reactor", panes = [
        pane("committer-reactor", serve = ["eventlog", "react", "--as", "cursor-committer", "--on", "result", "--timeout", "600s", "--git", "--", "eventlog", "action", "commit"], ready = output("watching"), on_start = ["eventlog", "lifecycle", "start", "cursor-committer", "--model", "composer-2.5-fast", "--paths", "."], on_stop = ["eventlog", "lifecycle", "stop", "cursor-committer"]),
    ])
    docs = herdr.tab("sonnet" + ": docs reactor", panes = [
        pane("docs-reactor", serve = ["eventlog", "react", "--as", "doc-worker", "--on", "ack", "--filter", "by=" + "cursor-committer", "--filter", "outcome=committed", "--timeout", "600s", "--", "eventlog", "action", "docs"], ready = output("watching"), after = ["committer-reactor"], on_start = ["eventlog", "lifecycle", "start", "doc-worker", "--model", "sonnet", "--paths", "docs,README.md,AGENTS.md"], on_stop = ["eventlog", "lifecycle", "stop", "doc-worker"]),
    ])
    return [committer, docs]
